import { Product } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Мастер и Маргарита',
    author: 'Михаил Булгаков',
    price: 850,
    oldPrice: 1200,
    category: 'Books',
    image: 'https://picsum.photos/400/600?random=1',
    rating: 4.9,
    reviewsCount: 1240,
    description: 'Бессмертная классика русской литературы. История о дьяволе, посетившем Москву.',
    tags: ['classic', 'fiction'],
    isNew: false,
    inStock: true,
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    price: 1500,
    category: 'Books',
    image: 'https://picsum.photos/400/600?random=2',
    rating: 4.8,
    reviewsCount: 8500,
    description: 'Практическое руководство по изменению привычек и улучшению жизни.',
    tags: ['business', 'psychology'],
    isNew: true,
    inStock: true,
  },
  {
    id: '3',
    title: 'Набор капиллярных ручек',
    price: 600,
    category: 'Stationery',
    image: 'https://picsum.photos/400/400?random=3',
    rating: 4.5,
    reviewsCount: 45,
    description: 'Набор из 12 цветов, толщина линии 0.4мм. Идеально для скетчинга.',
    tags: ['art', 'school'],
    inStock: true,
  },
  {
    id: '4',
    title: 'Ежедневник Moleskine',
    price: 2400,
    category: 'Stationery',
    image: 'https://picsum.photos/400/400?random=4',
    rating: 4.7,
    reviewsCount: 120,
    description: 'Классический черный ежедневник в твердой обложке.',
    tags: ['office', 'planning'],
    isNew: false,
    inStock: true,
  },
  {
    id: '5',
    title: 'Гарри Поттер и Философский камень',
    author: 'Дж. К. Роулинг',
    price: 900,
    category: 'Books',
    image: 'https://picsum.photos/400/600?random=5',
    rating: 5.0,
    reviewsCount: 5000,
    description: 'Начало великой истории о мальчике, который выжил.',
    tags: ['kids', 'fantasy'],
    inStock: true,
  },
  {
    id: '6',
    title: 'Акриловые краски, 24 цвета',
    price: 1800,
    oldPrice: 2200,
    category: 'Art',
    image: 'https://picsum.photos/400/400?random=6',
    rating: 4.6,
    reviewsCount: 89,
    description: 'Яркие, устойчивые к выцветанию краски для профессионалов и любителей.',
    tags: ['art', 'hobby'],
    inStock: true,
  },
  {
    id: '7',
    title: 'Sapiens. Краткая история человечества',
    author: 'Юваль Ной Харари',
    price: 1100,
    category: 'Books',
    image: 'https://picsum.photos/400/600?random=7',
    rating: 4.7,
    reviewsCount: 3200,
    description: 'Увлекательное путешествие по истории нашего вида.',
    tags: ['history', 'science'],
    inStock: false,
  },
  {
    id: '8',
    title: 'Подарочный набор "Вдохновение"',
    price: 3500,
    category: 'Sets',
    image: 'https://picsum.photos/400/400?random=8',
    rating: 4.9,
    reviewsCount: 15,
    description: 'Блокнот, ручка Parker и книга по искусству в красивой упаковке.',
    tags: ['gift', 'set'],
    isNew: true,
    inStock: true,
  },
];